# Generated by Django 6.0.5 on 2026-06-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='airtel_money_enabled',
            field=models.BooleanField(default=True, help_text='Enable Airtel Money payments'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cod_enabled',
            field=models.BooleanField(default=True, help_text='Enable Cash on Delivery'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_service_fee_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Default service commission percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_shipping_cost_per_kg',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Default international shipping cost per kg in USD', max_digits=8),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_usd_to_rwf_rate',
            field=models.DecimalField(decimal_places=2, default=1350.0, help_text='Default USD to RWF exchange rate', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mtn_momo_enabled',
            field=models.BooleanField(default=True, help_text='Enable MTN Mobile Money payments'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stripe_enabled',
            field=models.BooleanField(default=False, help_text='Enable Stripe card payments'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, default='Kigali, Rwanda'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='info@worldwideshopping.rw', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(default='RWF', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='currency_symbol',
            field=models.CharField(default='RWF', max_length=5),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://web.facebook.com/epurchaseworldwide/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(default='&copy; 2026 Worldwide e-shopping LTD. All rights reserved.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Worldwide e-shopping LTD', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='We help you buy products on Alibaba, Amazon, eBay, and many more...', max_length=300),
        ),
    ]
