# Generated by Django 6.0.5 on 2026-06-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('purchased_overseas', 'Purchased from Supplier'), ('in_transit', 'In Transit to Kigali'), ('customs', 'Customs Clearance'), ('in_kigali', 'Arrived in Kigali'), ('ready_pickup', 'Ready for Pickup/Delivery'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
    ]
