web: gunicorn worldwide.wsgi:application --bind 0.0.0.0:$PORT --workers 4 --threads 2 --worker-class gthread --log-file -
release: python manage.py migrate --noinput && python manage.py collectstatic --noinput
