# Generated by Django 6.0.5 on 2026-06-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_rwf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Mobile Money phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('stripe', 'Stripe (Card)'), ('paypal', 'PayPal'), ('mtn_momo', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cod', 'Cash on Delivery')], max_length=20),
        ),
    ]
