# Generated by Django 6.0.5 on 2026-06-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('countries', models.CharField(help_text='Comma-separated country names', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('method_type', models.CharField(choices=[('local', 'Local Delivery'), ('national', 'National Shipping'), ('international', 'International Shipping'), ('express', 'Express Delivery'), ('free', 'Free Shipping')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_above', models.DecimalField(decimal_places=2, default=0, help_text='Free shipping above this amount', max_digits=10)),
                ('estimated_days', models.CharField(default='3-5 business days', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='shipping.shippingzone')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
