# Generated by Django 6.0.5 on 2026-06-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name (e.g., laptop, shirt, home)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='calculated_price_rwf',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto-calculated final price in RWF', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_days',
            field=models.CharField(blank=True, default='10-14 days', help_text='Estimated delivery time for import items', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='origin_platform',
            field=models.CharField(blank=True, choices=[('alibaba', 'Alibaba (China)'), ('amazon', 'Amazon (USA)'), ('ebay', 'eBay (Global)'), ('trendyol', 'Trendyol (Turkey)'), ('aliexpress', 'AliExpress (China)'), ('other', 'Other')], help_text='Where this product is sourced from (Alibaba, Amazon, etc.)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original item price in USD on the source platform', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('local', 'Local Stock (Instant Delivery)'), ('import', 'Import On-Demand')], default='import', help_text='Local = instant delivery, Import = sourced from overseas', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='service_fee_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Service commission percentage (e.g., 10.00 = 10%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost_per_kg',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='International shipping cost per kg in USD (air cargo to Rwanda)', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, help_text='Paste the original product link here (e.g., alibaba.com/item/...)', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='usd_to_rwf_rate',
            field=models.DecimalField(decimal_places=2, default=1350.0, help_text='Current USD to RWF exchange rate', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg (used for import price calc)', max_digits=8, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type'], name='products_pr_product_cea9e6_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['origin_platform'], name='products_pr_origin__fff2e5_idx'),
        ),
    ]
